### ISSUE TITLE
 Portuguese Translation Progress Checklist

### ISSUE THREAD

**Issue by brunommpreto** [solidity-docs/pt-portuguese#1]
### Maintainer List

@dalloglio solidity-docs/.github#60

### Information for New Translators

To translate a page:

Check that no one else has claimed your page in the checklist and comments below.
Comment below with the name of the page you would like to translate. Please take only one page at a time.
Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and [style guide](https://docs.soliditylang.org/en/latest/contributing.html#documentation-style-guide) to understand how to translate various technical or Solidity/Ethereum-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

### For Maintainers

When someone likes to contribute, edit this issue with the username of the contributor, and with the PR. 

E.g. 
- [ ] index (@dalloglio)

When PRs are merged, make sure to mark that page as completed.

### Core Pages

These pages need to be translated before the translation will be added as a new language to the Solidity docs flyout menu. Please translate these pages first. 

#### Basics
- [x] index
- [x] intro-to-smart-contracts
- [x] installing-solidity
- [ ] solidity-by-example (@dalloglio)

#### Language Description
- [ ] layout-of-source-files
- [ ] structure-of-a-contract
- [ ] types
- [ ] units-and-global-variables
- [ ] control-structures
- [ ] contracts (@MurilloWolf)
- [ ] assembly
- [ ] cheatsheet
- [ ] grammar

#### Internals
- [ ] layout_in_storage
- [ ] layout_in_memory
- [ ] layout_in_calldata
- [ ] variable_cleanup
- [ ] source_mappings
- [ ] optimiser
- [ ] metadata
- [ ] abi-spec

#### Additional Material
- [ ] yul
- [ ] natspec-format
- [ ] security-considerations
- [ ] common-patterns

### Next Steps

These are the next most important translations, ordered by importance:

#### Additional Material

- [ ] using-the-compiler
- [ ] contributing
- [ ] 080-breaking-changes
- [ ] 070-breaking-changes
- [ ] 060-breaking-changes
- [ ] 050-breaking-changes
- [ ] resources
- [ ] bugs

### Additional Translations

These are not the primary translation targets but still a nice to have!

- [ ] style-guide
- [ ] brand-guide

_Credits: This doc is derived from the [Progress Template](https://github.com/reactjs/reactjs.org-translation/blob/master/PROGRESS.template.md) of the ReactJS Localization Team._

**Comment by schrodervictor** [comment]
As a native Portuguese speaker, I would like to present myself to support the translation effort, but I have a question: is this going to be an European or Brazilian Portuguese translation?

**Comment by dalloglio** [comment]
I am Brazilian and I am interested in contributing

**Comment by dalloglio** [comment]
I started translating Basics - index

**Comment by dalloglio** [comment]
I started translating Basics - intro-to-smart-contracts

**Comment by ghost** [comment]
Hello, I'm Brazilian and I'd like to help translate the documentation into Portuguese 🫡

**Comment by ghost** [comment]
I started translating ‘Language Description - layout-of-source-files’

**Comment by ghost** [comment]
> I started translating ‘Language Description - layout-of-source-files’

Translation completed! Please analyse and approve

**Comment by dalloglio** [comment]
> > I started translating ‘Language Description - layout-of-source-files’
> 
> Translation completed! Please analyse and approve

Hello! Could you please open a PR from your branch to the develop branch of this repository? This way, I can review your translations and approve them.

**Comment by dalloglio** [comment]
I started translating Basics - installing solidity
